nipApi: https://dane.biznes.gov.pl
tokenCeidg: tokenCeidg
tokenUrl: https://faktury.freeddns.org


spring:
  datasource:
    url: jdbc:postgresql://faktury.freeddns.org:5432/invoices
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: email
    password: pass
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true













