nipApi: https://wl-api.mf.gov.pl
tokenUrl: localhost:8080


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invoices
    username: postgres
    password: demon
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: fakturyapp11@gmail.com
    password: mmcgreeloddihaqv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true













