ceidgApi: https://dane.biznes.gov.pl
tokenCeidg: tokenCeidg
mfApi: https://wl-api.mf.gov.pl
tokenUrl: localhost:8080


spring:
  datasource:
    url: jdbc:postgresql://url:5432/invoices
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: email
    password: pass
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true













